### ISSUE TITLE
Don't re-build/install Tor or Tor Browser unnecessarily

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/FingerprintSecureDrop#18]
With some good use of `when:` statements in the playbook, we could avoid re-download/build/installing Tor and Tor Browser. This would save us _a lot_ of time when (re-)provisionining.

An original worry with TB was that our profile dir might be polluted as a result of normal operation of our crawler, but this should not actually happen as we're not installing or uninstalling extensions, making bookmarks, or otherwise performing other actions that should result in profile dir pollution. It also seems unlikely we will be doing anything such activities in the future.

As far as Tor goes, most of the tasks involving getting it set up on the system use `command:` which is not idempotent unless you make it so (using `when:` or other methods).

**Comment by psivesely** [comment]
Note, the Ansible `unarchive` module relies on `tar`'s own idempotence, which looks at file names, but does not hash the files. That's why we have been first removing the Tor Browser dir and then re-unarchiving it.

**Comment by conorsch** [comment]
After some in-person discussion, it looks like the `Clobber relay.c in Tor {{ tor_release }} with custom relay.c from repo` task in the crawler role is our best bet for determining whether to rebuild tor. Registering a var to inspect the changed status and conditionally running the subsequent tasks:
- `Configure Tor {{ tor_release }}`
- `Make Tor {{ tor_release }}`
- `Install Tor {{ tor_release }}`

would make the build idempotent. This approach also catches the case where the tor_release var has changed, since that will extract a new tarball, and thus cause the clobber task to register changed as well.

While we're at it, let's modify the clobber task to use the `patch` module rather than `copy`, since technically we're patching an existing C file. We'll still be able to register and inspect the changed status as described above.

**Comment by psivesely** [comment]
Fixed in https://github.com/freedomofpress/FingerprintSecureDrop/commit/d9b5c29590b157515a52872f0957827901c67774
